# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bloggrs API Documentation
email: your-email@example.com
description: >-
  Documentation for the Bloggrs API, a modern blogging platform built with Prisma, GraphQL, and Vue.js.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Just the Docs theme settings
just_the_docs:
  # Main navigation
  nav_footer: false
  nav_external_links: true
  nav_external_links_new_tab: true

  # Aux links for the upper right navigation
  aux_links:
    "Bloggrs on GitHub":
      - "//github.com/yourusername/bloggrs"

  # Color scheme currently only supports "dark" or nil (default)
  color_scheme: nil

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
